services:

  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sample
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d sample" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    build: .
    volumes:
      - .:/code
    env_file:
      - compose.env
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - compose.env
    ports:
      - 5050:80
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: